name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: deploy

    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initalize Terraform
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.GCS_BACKEND_BUCKET_NAME }}"
        working-directory: ./infra

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: ./infra
